- name: Add origin
  ansible.builtin.shell: git remote add gitlab "https://root:{{ root_password }}@{{ gitlab_host }}/development/windows-templates"
  ignore_errors: True
- name: Push templates
  ansible.builtin.shell: git push gitlab add-rhdh-templates